name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.0
  percent_indicator: ^4.2.5
  auto_route: 
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner:
  freezed:
  mocktail:
  flutter_gen_runner:
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding_backgrounds/
